### PR TITLE
[202305] Checkout correct branch from sonic-mgmt-common and sonic-swss-common during pipeline build

### PR DESCRIPTION
**Pull request by sachinholla**
#### Why I did it

Pipeline is always fetching latest of sonic-mgmt-common and sonic-swss-common repos for its builds. They must be use source code from 202305 branch

#### How I did it

Checkout latest from `$(System.PullRequest.TargetBranch)` during PR builds and from `$(Build.SourceBranchName)` during manual builds.

Known issue: other pipeline artefacts are still being downloaded from master branch. Not a blocker as of now.

#### How to verify it

Pipeline build

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Comment by sachinholla** [comment]
Yes @ganglyu, I want to have a permanent fix for this dependency. But I need 202305 branch in sonic-mgmt-common repo first. I had requested Yanzhao to create the branch earlier, but it is not ready yet. Will remind him again.

**Comment by ganglyu** [comment]
@sachinholla please reply my email and provide your detailed requirement for us.

**Review by ganglyu — APPROVED** [review]

**Comment by maipbui** [comment]
@sachinholla Please merge latest master code to trigger Semgrep.

**Comment by sachinholla** [comment]
@maipbui, master branch has many additional changes and cannot be merged to 202305. If the semgrep check requires any code change, isn't it best to disable it on the old branches?

**Comment by maipbui** [comment]
@sachinholla maybe you can create a new PR. Semgrep is enforced on 07/03. Any PRs created before enforce timestamp 07/03 have hanging status check like in your PR. Our solution is usually to merge latest master code to trigger Semgrep. I think if you create new PR, which is after enforce timestamp, your new PR will not include Semgrep in status check. e.g. https://github.com/sonic-net/sonic-utilities/pull/2891/checks

**Comment by sachinholla** [comment]
@maipbui, I cherry picked https://github.com/sonic-net/sonic-gnmi/commit/fd78c42 and it seems working now

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
